import React from 'react';
import { mount } from 'enzyme';
import ErrorBoundary from "../ErrorBoundary";
import renderer from 'react-test-renderer';

const ComponentWithError = () => { throw new Error();};

describe('ErrorBoundary window',() => {
    it('should match the snapshot', () => {
        const tree = renderer.create(<ErrorBoundary><ComponentWithError/></ErrorBoundary> ).toJSON();
        expect(tree).toMatchSnapshot();
    });

    it('displays error message on error generated by child', () => {
        const wrapper = mount(
            <ErrorBoundary >
                <ComponentWithError />
            </ErrorBoundary>
        );
        expect(wrapper.find('h1').text()).toEqual('Error');
    });
});
